### PR TITLE
Update About activity.

### PR DESCRIPTION
**Pull request by alaskalinuxuser**
Here are my commits for updating the about activity. As you can see, the text you posted on F-Droid shows up as the about information, as well as the license display. The license is clickable, which will forward you to the GPL.
 One the bottom are three floating action buttons, one to return to the main activity, one for your website, and one for your github.

### CODE REVIEW

**Comment by alaskalinuxuser** [comment]
about_easer

**Comment by alaskalinuxuser** [comment]
Also, I have no issue if you want to change anything. You are welcome to edit anything to suit your needs! :D

**Comment by renyuneyun** [comment]
Hi. Thanks a lot!
The only change I'm going to do is to make "back" fab go back in the webview (for adding more info in the about page in the future) :)

By the way, what address (email, website or github) would you like to show in a "contributer" file / page?

**Comment by alaskalinuxuser** [comment]
No problem either way! I'm new to programming (I'm taking an android dev course) so if there is a better way, fell free to do that, it will not hurt my feelings at all! Actually, this was the first pull request I've ever done.
You can use my github as my contact info, thanks.
I look forward to seeing your project grow, and thanks for letting me help out in this small way!

**Comment by renyuneyun** [comment]
Merged.

Yeah, coding is fun.

Maybe you could try to give better names for functions / methods in the future :P (well I'm not very good at that either)

**Pull request merged**
