### PR TITLE
Updated da_DK translations

### PR DESCRIPTION
**Pull request by twikedk**
Some updates, reviews a.m.

### CODE REVIEW

**Comment by renyuneyun** [comment]
Wow :p
Thank you




There is going to be some amends of existing string resources (mainly dropping the colon mark ":"). If you are going to update the translation then, I'll let you know what those resources will be (they are not edited yet).

**Comment by renyuneyun** [comment]
By the way, I'm not sure, but maybe the string resource
```
<string name="condition_cell_location">@string/event_celllocation</string>
```
doesn't need to present in the translation.
There will be more similar ones recently.

If the previous one (`event_celllocation`) is removed, I'll keep this (pointer) updated.

**Comment by twikedk** [comment]
Yep I also had my doubt if it needed to be included but as it wasn't marked with a translatable="false" I chose to include it.
Have you by the way considered to move translation to transifex, crowdin or the like? As far as I know they accept open source projects for free. It will make it easier for the translators as of right now I compare both files with a diff utility and must admit I sometimes have to go over it 2-3 times before I catch all the differences.
Sorry for the long feedback :-)

**Comment by renyuneyun** [comment]
Hi, I did some changes to existing string resources. These are affected ones (which, in furthur translation, shall be updated):
`profile_indicator_last`
`profile_indicator_from`
`text_title`
`text_parent`
`text_profile`
and all string resources with `scenario` (because "Scenario" is renamed to "Event").

**Pull request merged**
