### PR TITLE
Fix Unittests (testPluginData)

### PR DESCRIPTION
**Pull request by idealist1508**
- LaunchAppOperationData.extras is nonnull

### CODE REVIEW

**Comment by idealist1508** [comment]
Please review my fix. I am new in java, android development.

**Comment by renyuneyun** [comment]
Hi there,
Thanks for pointing out that there is a mismatch of nullability.
However, to me, the fix should not be "make it NonNull". The change only has to be "make it work correctly for Nullable `extras`" (i.e. check `extras == null` before calling `equals()`, or use the helper function from `Utils`).
This element (`extras`) should be Nullable, at least the semantics is more intuitive to me in this way.

**Comment by renyuneyun** [comment]
And, by the way, there doesn't seem to be an error in the unittest. The test is correct and passes, although not full covered.
If you want it to cover the cases when `extras` is not `null`, you can add a test case. But the existing semantics should remain unchanged unless there is a good reason.

**Comment by idealist1508** [comment]
> The test is correct and passes.
Nop
image

**Comment by idealist1508** [comment]
> This element (extras) should be Nullable, at least the semantics is more intuitive to me in this way.
I like Null Object Pattern, but it is your decision how should look your code. I will do PR with null checks.

**Comment by renyuneyun** [comment]
> Nop
Hmm, thanks for identifying... I should have set up the CI better.

**Pull request closed without merging**
