### PR TITLE
Notification event fix

### PR DESCRIPTION
**Pull request by grmoth**
Fix notification received event when Title or content is SpannableString (hopefully)
Related to issues  #389 and maybe #366

### CODE REVIEW

**Comment by renyuneyun** [comment]
Thanks very much for providing this patch!
It seems to work, but I didn't find any source documents for the necessity of using this specific method. Would you mind sharing the relevant information?

**Comment by grmoth** [comment]
Hi,
First I must say I know nothing about java programming, this commit is only based on my understanding of the log, which may be inaccurate.

StackOverflow has several example of snippet for reading notification content, using XX.getCharSequence(YY).getString(), for example [here ](https://stackoverflow.com/questions/22330809/getting-detail-expanded-text-from-an-android-notification) or [here](https://stackoverflow.com/questions/65841242/getstringandroid-text-returns-spannablestring-instead-of-string). But that would fail if XX.getCharSequence(YY) == null, so I added a intermediate check. Thinking again now, it may probably be better to use a conditional assignment to avoid the intermediate variables and check, with the same result.

**Comment by renyuneyun** [comment]
Thanks!
It seems to be right. I'll merge it, and see it anyone complains in the beta release.

I'll do a squash merge.

**Comment by Mageek627** [comment]
Thanks @grmoth !
Could we get an apk @renyuneyun ? / Do you plan on updating the F-droid version ?
Thanks in advance.

**Pull request merged**
