### PR TITLE
Updated danish strings.xml and plugins.xml

### PR DESCRIPTION
**Pull request by twikedk**

### CODE REVIEW

**Comment by twikedk** [comment]
Hm I sent along the 2 patches too which not was intended, it should only have been the updated strings and plugins xml files :-(

**Comment by renyuneyun** [comment]
Hi there.
I can merge it, of course. But would you like to make the commit history cleaner?

If you have no idea where to start, I can provide some suggestions :)

**Comment by twikedk** [comment]
Yes please provide some suggestions, I'm not sure I understand what you mean with making it cleaner?

**Comment by renyuneyun** [comment]
I should use "neat" to replace "cleaner" LOL

Suggestions are in two parts:
1. The quickest method to make the commit history in you current repo neat
2. Tips to avoid this kind of thing/problem in the future

## Make the current repo neat

The problem of the current commit history is that there are many unneeded small commits and merges. These are unnecessary if we see the change is only for updating the translation.

As you already have the (updated) files (string.xml, plugins.xml), you can directly create a commit containing them (with a proper commit message, absolutely). The only trick is to (re)set your *HEAD* to the point where my repo's master branch is, while keeping your *working space* unchanged (compared with the current status, i.e. containing the updated string.xml and plugins.xml). The following commands will do all these stuffs (and you need to provide a commit message, of course).
```
git reset --soft ebb5e6e99c7ea5ece3d8c64f345256de78c7b455  # do the trick; ebb5e6e99c7ea5ece3d8c64f345256de78c7b455 is the commit id of the current master branch of my repo. Note you don't have to perform "git add" for this case, because "git reset" will make those files added to the cache
git commit  # create a new commit containing both changes
```

Then you should push the change to your github repo. Note that we have changed the master branch of your repo, and this is inconsistent with what is in the current github repo. Therefore, you need to "force push" the change.
```
git push --force origin master
```
where "origin" should be the the remote source of **your** github repo (this is typically "origin" if you cloned the repo from **your** github repo).

## Avoid in the future
I think learning the basic concepts of git first is useful, if you don't immediately understand what *HEAD* or *branch* means.

If you are using a tool (e.g. Android Studio) which manages git for you, I'd suggest not enabling "auto commit" (if there is such option) -- manage all commits manually, by yourself.

Try to stay on one branch when modifying / updating things, and create Pull Requests on that branch (as source). There is no real difference between a "master" branch and other branches -- it is only that people (not git) tend to consider "master" as a "main" branch.

Use `git add XXXXXX` more frequently than `git commit`. You may find many suggestions about the balance between more commits vs bigger commits...

You can also "patch" the previous commit (by creating a squash commit to replace the previous commit), by using `git commit --amend`.

**Comment by twikedk** [comment]
Then I guess I have to explain how I normally do/intend to do it. First of all I don't run any local repos as I only use what github makes available for me at the time being, this goes for Easer and some other 2-3 projects I participate in doing translations.
Normally I check **values/strings.xml** & **values/plugins.xml** to see if there are newer versions. Then I make a fork of the project. Next I update the danish translation with the new strings. Then I should make a pull req to my forked project and merge the changes into that. After that I should remember to delete the patches as they no longer are needed :-)
With this newly updated forked project I now make a pull req up against your Easer project which should result in you getting only these 2 updated files??

**Comment by twikedk** [comment]
Is this pull req. wating for some action from my side??

**Comment by renyuneyun** [comment]
@twikedk Sorry I was busy during the week and forgot...

I'm not quite familar with the web workspace of github, but IIRC: you don't **have to** create a new branch when editing a file (so that you don't have to create a merge request on your side); when dealing with a merge request, you can choose (in the pull down list) to *squash* the commits (i.e. by choosing "Squash and merge").

So, you can create "one" new branch (when editing the first translation file), edit two files separately *on that branch*, and then (create pull request and choose) squash and merge (on your github repo), and finally create pull request here.

I'll squash and merge this pull request now, since github doesn't provide a convinent way (web interface) to significant manipulate the commit history (and there is no point to copy and paste around).
Hope you can make a better history in the future :)

**Pull request merged**
